name: gravenhorst_adults_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.1.0+1
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  freezed: ^1.0.0
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  location: ^4.3.0
  logger: ^1.1.0
  path_provider: ^2.0.7
  provider: ^6.0.1
  retry: ^3.1.0
  shared_preferences: ^2.0.9

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: DIN Alternate
      fonts:
        - asset: assets/fonts/DIN_Alternate_Black.ttf
          weight: 800
        - asset: assets/fonts/DIN_Alternate_Bold.ttf
          weight: 600
        - asset: assets/fonts/DIN_Alternate_Medium.ttf
          weight: 500
        - asset: assets/fonts/DIN_Alternate.ttf
          weight: 400
        - asset: assets/fonts/DIN_Alternate_Light.ttf
          weight: 300

    - family: DIN
      fonts:
        - asset: assets/fonts/DIN_Black.ttf
          weight: 800
        - asset: assets/fonts/DIN_Bold.ttf
          weight: 600
        - asset: assets/fonts/DIN_Medium.ttf
          weight: 500
        - asset: assets/fonts/DIN.ttf
          weight: 400
        - asset: assets/fonts/DIN_Light.ttf
          weight: 300
