name: gravenhorst_adults_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  audioplayers: ^0.20.1
  cached_network_image: ^3.1.0+1
  dartz: ^0.10.0
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_map_location_marker: ^2.0.0
  flutter_map_marker_cluster: ^0.4.4
  fluttertoast: ^8.0.8
  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  geolocator: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  imageview360:
    path: ../POCs/flutter_imageview_360/
  injectable: ^1.5.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  location: ^4.3.0
  logger: ^1.1.0
  page_transition: ^2.0.5
  path_provider: ^2.0.7
  percent_indicator: ^3.4.0
  provider: ^6.0.1
  retry: ^3.1.0
  shared_preferences: ^2.0.9
  tuple: ^2.0.0
  video_player: ^2.2.7
  video_thumbnail: ^0.4.6

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/

  fonts:
    - family: DIN
      fonts:
        - asset: assets/fonts/DIN_Black.ttf
          weight: 800
        - asset: assets/fonts/DIN_Bold.ttf
          weight: 600
        - asset: assets/fonts/DIN_Medium.ttf
          weight: 500
        - asset: assets/fonts/DIN.ttf
          weight: 400
        - asset: assets/fonts/DIN_Light.ttf
          weight: 300
